/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Pl2Project.*;
import java.util.ArrayList;

/**
 *
 * @author Mohammed
 */
public class EntryGUI extends javax.swing.JFrame {

    /**
     * Creates new form EntryGUI
     */
    public EntryGUI() {
        initComponents();
        bID.setVisible(false);
        bPN.setVisible(false);
        bDate.setVisible(false);
        pID.setVisible(false);
        pPN.setVisible(false);
        pDate.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonCustomerTicket = new javax.swing.JButton();
        jTextFieldCustomerPlateNumber = new javax.swing.JTextField();
        jButtonBackFEntryTCustomer = new javax.swing.JButton();
        bID = new javax.swing.JLabel();
        bPN = new javax.swing.JLabel();
        bDate = new javax.swing.JLabel();
        pID = new javax.swing.JTextField();
        pPN = new javax.swing.JTextField();
        pDate = new javax.swing.JTextField();
        m = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ticket");

        jLabel1.setText("Enter Your Plate Number");

        jButtonCustomerTicket.setText("Print Your Ticket");
        jButtonCustomerTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCustomerTicketActionPerformed(evt);
            }
        });

        jTextFieldCustomerPlateNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCustomerPlateNumberActionPerformed(evt);
            }
        });

        jButtonBackFEntryTCustomer.setText("Back");
        jButtonBackFEntryTCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackFEntryTCustomerActionPerformed(evt);
            }
        });

        bID.setText("ID");

        bPN.setText("PLATE NUMBER");

        bDate.setText("DATE");

        pID.setEditable(false);
        pID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pIDActionPerformed(evt);
            }
        });

        pPN.setEditable(false);
        pPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pPNActionPerformed(evt);
            }
        });

        pDate.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonBackFEntryTCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel1)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCustomerPlateNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(bID)
                                    .addGap(26, 26, 26)
                                    .addComponent(pID, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(m, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(bPN)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(pPN))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(bDate)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(pDate, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jButtonCustomerTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 258, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCustomerPlateNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonCustomerTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(m)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bID)
                    .addComponent(pID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bPN))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jButtonBackFEntryTCustomer)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCustomerPlateNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCustomerPlateNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCustomerPlateNumberActionPerformed

    private void jButtonBackFEntryTCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackFEntryTCustomerActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        CustomerGUI c = new CustomerGUI();
        c.setLocation(450,150);
        c.setVisible(true);
    }//GEN-LAST:event_jButtonBackFEntryTCustomerActionPerformed

    private void pPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pPNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pPNActionPerformed

    private void jButtonCustomerTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCustomerTicketActionPerformed
        // TODO add your handling code here:
        Customer c = new Customer();
        int flag = 1;
//        ArrayList<Customer> Customers = new ArrayList<Customer>();
        String x = jTextFieldCustomerPlateNumber.getText();
        if(! x.equals("")){
         c.loadFromFile();
        for(Customer c1:c.Customers){
          if(c1.plateNumber.equals(x)){
            flag=0;
            break;
          } 
                                    }
        if(flag == 1){
          c.printId(x);
          m.setText("");
          bID.setVisible(true);
          bPN.setVisible(true);
          bDate.setVisible(true);
          pID.setText(c.id+"");
          pPN.setText(c.plateNumber);
          pDate.setText(c.date);
          pID.setVisible(true);
          pPN.setVisible(true);
          pDate.setVisible(true);
        }
        else{
          m.setText("This Car is exist in The Parking");
        }    
        }
        else
         m.setText("Enter Your Plate Number");
    }//GEN-LAST:event_jButtonCustomerTicketActionPerformed

    private void pIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EntryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EntryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EntryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EntryGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bDate;
    private javax.swing.JLabel bID;
    private javax.swing.JLabel bPN;
    private javax.swing.JButton jButtonBackFEntryTCustomer;
    private javax.swing.JButton jButtonCustomerTicket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextFieldCustomerPlateNumber;
    private javax.swing.JLabel m;
    private javax.swing.JTextField pDate;
    private javax.swing.JTextField pID;
    private javax.swing.JTextField pPN;
    // End of variables declaration//GEN-END:variables
}
