/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AdminFrames;

import GUI.*;
import Pl2Project.*;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Mohammed
 */
public class SpotsFrame extends javax.swing.JFrame {

    /**
     * Creates new form SpotsFrame
     */
    public SpotsFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonBaxktoAdmin = new javax.swing.JButton();
        jButtonAddSpots = new javax.swing.JButton();
        jTextFieldAddspots = new javax.swing.JTextField();
        jButtonviewTotalSpots = new javax.swing.JButton();
        jLabeltotalSpots = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelAddSpots = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin");

        jButtonBaxktoAdmin.setText("Back");
        jButtonBaxktoAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBaxktoAdminActionPerformed(evt);
            }
        });

        jButtonAddSpots.setText("Add Spots");
        jButtonAddSpots.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddSpotsActionPerformed(evt);
            }
        });

        jTextFieldAddspots.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAddspotsActionPerformed(evt);
            }
        });

        jButtonviewTotalSpots.setText("View Total Spots");
        jButtonviewTotalSpots.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonviewTotalSpotsActionPerformed(evt);
            }
        });

        jLabel2.setText("Enter Number Of Spots");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonBaxktoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonAddSpots)
                        .addGap(333, 333, 333))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonviewTotalSpots))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldAddspots, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(jLabeltotalSpots, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(43, 43, 43)
                        .addComponent(jLabelAddSpots, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAddspots, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelAddSpots))
                .addGap(33, 33, 33)
                .addComponent(jButtonAddSpots)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonviewTotalSpots)
                    .addComponent(jLabeltotalSpots))
                .addGap(48, 48, 48)
                .addComponent(jButtonBaxktoAdmin)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldAddspotsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAddspotsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAddspotsActionPerformed

    private void jButtonBaxktoAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBaxktoAdminActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        AdminGUI a = new AdminGUI();
        a.setLocation(450,150);
        a.setVisible(true);
    }//GEN-LAST:event_jButtonBaxktoAdminActionPerformed

    private void jButtonAddSpotsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddSpotsActionPerformed
        // TODO add your handling code here:
        if (! jTextFieldAddspots.getText().equals("")){
           int spots = Integer.parseInt(jTextFieldAddspots.getText());
           Admin x = new Admin();
            try {
                x.addSpots(spots);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(SpotsFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
           jLabelAddSpots.setText("Add Successfully");
           reset();
        }
        else
            jLabelAddSpots.setText("Enter Number");
    }//GEN-LAST:event_jButtonAddSpotsActionPerformed

    private void jButtonviewTotalSpotsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonviewTotalSpotsActionPerformed
        // TODO add your handling code here:
        Admin a = new Admin();
        int size = 0;
        try {
            size = a.getParkingSize();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(SpotsFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        jLabeltotalSpots.setText( size +" Spots");
        
    }//GEN-LAST:event_jButtonviewTotalSpotsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SpotsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SpotsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SpotsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SpotsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SpotsFrame().setVisible(true);
            }
        });
    }
    protected void reset(){
    jTextFieldAddspots.setText("");
    jLabeltotalSpots.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddSpots;
    private javax.swing.JButton jButtonBaxktoAdmin;
    private javax.swing.JButton jButtonviewTotalSpots;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAddSpots;
    private javax.swing.JLabel jLabeltotalSpots;
    private javax.swing.JTextField jTextFieldAddspots;
    // End of variables declaration//GEN-END:variables
}
