/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AdminFrames;

import Pl2Project.*;

/**
 *
 * @author Mohammed
 */
public class UpdateUsersPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateUsersPanel
     */
    public UpdateUsersPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        unupdate = new javax.swing.JTextField();
        pupdate = new javax.swing.JTextField();
        jButtonSearchUsers = new javax.swing.JButton();
        SearchbyUsername = new javax.swing.JTextField();
        jobTitleUpdate = new javax.swing.JComboBox<>();
        jButtonUpdateuser = new javax.swing.JButton();
        jButtonDeleteuser = new javax.swing.JButton();
        Searchm = new javax.swing.JLabel();

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        jLabel3.setText("Job Title");

        pupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pupdateActionPerformed(evt);
            }
        });

        jButtonSearchUsers.setText("Search");
        jButtonSearchUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchUsersActionPerformed(evt);
            }
        });

        jobTitleUpdate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Operator" }));
        jobTitleUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobTitleUpdateActionPerformed(evt);
            }
        });

        jButtonUpdateuser.setText("Update");
        jButtonUpdateuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateuserActionPerformed(evt);
            }
        });

        jButtonDeleteuser.setText("Delete");
        jButtonDeleteuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteuserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jButtonUpdateuser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonDeleteuser))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pupdate)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jobTitleUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(unupdate)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(SearchbyUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonSearchUsers))
                                    .addComponent(Searchm, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(112, 112, 112))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSearchUsers)
                    .addComponent(SearchbyUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Searchm, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unupdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pupdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jobTitleUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUpdateuser)
                    .addComponent(jButtonDeleteuser))
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pupdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pupdateActionPerformed

    private void jobTitleUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobTitleUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jobTitleUpdateActionPerformed

    private void jButtonSearchUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchUsersActionPerformed
        // TODO add your handling code here:
        if(!SearchbyUsername.getText().equals("")){
        Admin a = new Admin();
        Person p = new Person();
        if(a.personIsExist(SearchbyUsername.getText())){
           p = a.returnPersonData(SearchbyUsername.getText());
           setPanelData(p);
           Searchm.setText("");  
        }
        else
           Searchm.setText("Not Found");        }
        else
          Searchm.setText("Enter username to search");

    }//GEN-LAST:event_jButtonSearchUsersActionPerformed

    private void jButtonUpdateuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateuserActionPerformed
        // TODO add your handling code here:
        String oldUname = SearchbyUsername.getText();
        Person x = new Person();
        Admin a = new Admin();
        
        if(! unupdate.getText().equals("") && !pupdate.getText().equals("")){
        x.name = unupdate.getText();
        x.password = pupdate.getText();
        if(jobTitleUpdate.getSelectedItem().equals("Admin"))
           x.jobTitle = "admin";
        else
           x.jobTitle = "operator";
        
        if(a.updatePerson(oldUname, x)) {
            Searchm.setText("Updated Successfully");
        }
         else
            Searchm.setText("Username is already exist");
        }
        else
          Searchm.setText("Failed to Update");

    }//GEN-LAST:event_jButtonUpdateuserActionPerformed

    private void jButtonDeleteuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteuserActionPerformed
        // TODO add your handling code here:
        if(! unupdate.getText().equals("")){
        Admin a = new Admin();
        
        if(a.deletePerson(unupdate.getText())){
            Searchm.setText("Deleted Successfully");
            reset();
        }
        else
             Searchm.setText("Failed to Delete");
        }
        else
             Searchm.setText("Missing required Fields");
    }//GEN-LAST:event_jButtonDeleteuserActionPerformed
    protected void setPanelData(Person x){
    unupdate.setText(x.name);
    pupdate.setText(x.password);
    if(x.jobTitle.equals("admin"))
      jobTitleUpdate.setSelectedItem("Admin");
    else
      jobTitleUpdate.setSelectedItem("Operator");

    }
    protected void reset(){
      unupdate.setText("");
      pupdate.setText("");
      SearchbyUsername.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SearchbyUsername;
    private javax.swing.JLabel Searchm;
    private javax.swing.JButton jButtonDeleteuser;
    private javax.swing.JButton jButtonSearchUsers;
    private javax.swing.JButton jButtonUpdateuser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> jobTitleUpdate;
    private javax.swing.JTextField pupdate;
    private javax.swing.JTextField unupdate;
    // End of variables declaration//GEN-END:variables
}
