/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AdminFrames;

import GUI.*;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

/**
 *
 * @author Mohammed
 */
public class UsersFrame extends javax.swing.JFrame {

    /**
     * Creates new form UsersFrame
     */
    AddUsersPanel aup;
    UpdateUsersPanel uup;
    ListUsersPanel lup;
    GridBagLayout layout = new GridBagLayout();
    
    public UsersFrame() {
        initComponents();
        aup = new AddUsersPanel();
        uup = new UpdateUsersPanel();
        lup = new ListUsersPanel();
        UserShowPanel.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        UserShowPanel.add(aup,c);
        UserShowPanel.add(uup,c);
        UserShowPanel.add(lup,c);
        aup.setVisible(true);
        uup.setVisible(false);
        lup.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserButtonPanel = new javax.swing.JPanel();
        GoToAddUsers = new javax.swing.JButton();
        GoToListUsers = new javax.swing.JButton();
        GoToUpdateUsers = new javax.swing.JButton();
        UserShowPanel = new javax.swing.JPanel();
        backtoadmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin");

        GoToAddUsers.setText("Add Users");
        GoToAddUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoToAddUsersActionPerformed(evt);
            }
        });

        GoToListUsers.setText("List Users");
        GoToListUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoToListUsersActionPerformed(evt);
            }
        });

        GoToUpdateUsers.setText("Update / Delete");
        GoToUpdateUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoToUpdateUsersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UserShowPanelLayout = new javax.swing.GroupLayout(UserShowPanel);
        UserShowPanel.setLayout(UserShowPanelLayout);
        UserShowPanelLayout.setHorizontalGroup(
            UserShowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 528, Short.MAX_VALUE)
        );
        UserShowPanelLayout.setVerticalGroup(
            UserShowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        backtoadmin.setText("Back");
        backtoadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtoadminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UserButtonPanelLayout = new javax.swing.GroupLayout(UserButtonPanel);
        UserButtonPanel.setLayout(UserButtonPanelLayout);
        UserButtonPanelLayout.setHorizontalGroup(
            UserButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UserButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UserButtonPanelLayout.createSequentialGroup()
                        .addGroup(UserButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(GoToUpdateUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(GoToListUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(GoToAddUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserButtonPanelLayout.createSequentialGroup()
                        .addComponent(backtoadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)))
                .addComponent(UserShowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        UserButtonPanelLayout.setVerticalGroup(
            UserButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserButtonPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(GoToAddUsers)
                .addGap(50, 50, 50)
                .addComponent(GoToListUsers)
                .addGap(55, 55, 55)
                .addComponent(GoToUpdateUsers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backtoadmin)
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserButtonPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(UserShowPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(UserButtonPanel, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GoToAddUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoToAddUsersActionPerformed
        // TODO add your handling code here:
        aup.setVisible(true);
        uup.setVisible(false);
        lup.setVisible(false);
    }//GEN-LAST:event_GoToAddUsersActionPerformed

    private void GoToListUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoToListUsersActionPerformed
        // TODO add your handling code here:
        aup.setVisible(false);
        uup.setVisible(false);
        lup.setVisible(true);
    }//GEN-LAST:event_GoToListUsersActionPerformed

    private void GoToUpdateUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoToUpdateUsersActionPerformed
        // TODO add your handling code here:
        aup.setVisible(false);
        uup.setVisible(true);
        lup.setVisible(false);
    }//GEN-LAST:event_GoToUpdateUsersActionPerformed

    private void backtoadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtoadminActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        AdminGUI a = new AdminGUI();
        a.setLocation(450,150);
        a.setVisible(true);
    }//GEN-LAST:event_backtoadminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsersFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GoToAddUsers;
    private javax.swing.JButton GoToListUsers;
    private javax.swing.JButton GoToUpdateUsers;
    private javax.swing.JPanel UserButtonPanel;
    private javax.swing.JPanel UserShowPanel;
    private javax.swing.JButton backtoadmin;
    // End of variables declaration//GEN-END:variables
}
